import {createAction} from 'redux-actions';

export default {
  'LIBRARY/FETCH_CATEGORIES_SUCCESSFULLY': createAction('LIBRARY/FETCH_CATEGORIES_SUCCESSFULLY'),
  'LIBRARY/FETCH_CATEGORIES_ERROR': createAction('LIBRARY/FETCH_CATEGORIES_ERROR'),
  'LIBRARY/FETCH_CATEGORIES': createAction('LIBRARY/FETCH_CATEGORIES'),
};
